# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SV4VUBd2A-RdCCFO0iY33nxm6bviDtG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(0)

df_dict = {}

product_names = ['Milk', 'Cheese', 'Yogurt', 'Butter', 'Cream', 'Eggs', 'IceCream', 'CottageCheese', 'SourCream', 'WhippedCream']

dates = pd.date_range(start='1/1/2023', end='12/31/2023')

for name in product_names:
    demand_data = np.random.uniform(low=50, high=100, size=len(dates))
    supply_data = np.random.uniform(low=50, high=100, size=len(dates))


    holidays = ['2023-02-14', '2023-07-04', '2023-11-25', '2023-12-25']

    # demand_data[pd.to_datetime(holidays) == dates] *= 1.3  # increase demand by 30% on holidays

    demand_data[dates.isin(pd.to_datetime(holidays))] *= 3  # increase demand by 30% on holidays



    supply_data[dates.isin(pd.to_datetime(holidays))] *= 2.5  # increase supply by 250% on holidays


    thanksgiving = '2023-11-25'
    christmas = '2023-12-25'
    supply_data[dates == pd.to_datetime(thanksgiving)] *= 4  # quadruple supply on Thanksgiving
    supply_data[dates == pd.to_datetime(christmas)] *= 5 # quintuple supply on Christmas

    blizzard_date = '2023-12-20'
    pre_blizzard_date = '2023-12-19'

    demand_data[dates == pd.to_datetime(blizzard_date)] *= 2  # double the demand on blizzard date
    demand_data[dates == pd.to_datetime(pre_blizzard_date)] /= 2  # halve the demand on pre-blizzard date

    # Calculate inventory
    inventory_data = supply_data - demand_data

    # Make sure inventory is not less than zero
    inventory_data = np.where(inventory_data < 0, 0, inventory_data)

    df = pd.DataFrame({
        'Date': dates,
        'Demand': demand_data,
        'Supply': supply_data,
        'Inventory': inventory_data
    })

    df_dict[name] = df

fig, ax = plt.subplots(figsize=(12, 6))

ax.plot(dates, demand_data, label='Demand')
ax.plot(dates, supply_data, label='Supply')
ax.plot(dates, inventory_data, label='Inventory')

ax.set(xlabel='Date', ylabel='Quantity',
       title='Demand, Supply and Inventory over time')
ax.legend()

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dates = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')

product_names = ['Milk']

holidays = ['2022-11-24', '2022-12-25']  # Thanksgiving and Christmas
blizzard = ['2022-02-10', '2022-02-11', '2022-02-12', '2022-02-13']

for product in product_names:
    sales_data = np.random.uniform(50, 100, len(dates))  # changed to 'np.random.uniform' to generate float64 type data
    demand_data = np.random.uniform(100, 140, len(dates))  # changed to 'np.random.uniform' to generate float64 type data
    inventory_data = demand_data - sales_data

    for holiday in holidays:
        demand_data[pd.to_datetime(holiday) == dates] *= 1.3  # increase demand by 30% on holidays

    for day in blizzard:
        demand_data[pd.to_datetime(day) == dates] *= 2  # double the demand during the blizzard

    data = pd.DataFrame({
        'Date': dates,
        'Product': product,
        'Sales': sales_data,
        'Demand': demand_data,
        'Inventory': inventory_data
    })

    print(data.head())

    plt.figure(figsize=(12, 6))
    plt.plot(data['Date'], data['Sales'], label='Sales')
    plt.plot(data['Date'], data['Demand'], label='Demand')
    plt.plot(data['Date'], data['Inventory'], label='Inventory')

    plt.xlabel('Date')
    plt.ylabel('Value')
    plt.title(f'{product} - Sales, Demand, and Inventory over Time')
    plt.legend()
    plt.grid(True)
    plt.show()